services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - "./keycloak-extension-rest/target/keycloak-extension-rest-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-extension-rest.jar"
      - "./keycloak-extension-rest/src/test/resources/conciso-realm.json:/opt/keycloak/data/import/conciso-realm.json"
      - "./authenticator-required-action/target/authenticator-required-action-1.0-SNAPSHOT.jar:/opt/keycloak/providers/authenticator-required-action.jar"
      - "./authenticator-required-action/src/test/resources/required-action-realm.json:/opt/keycloak/data/import/required-action-realm.json"
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:11.14-alpine
    command: postgres -c 'max_connections=300' -c 'shared_buffers=80MB'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d keycloak
      interval: 5s
      timeout: 3s
      retries: 10
